### ISSUE TITLE
Permission to use + Faulty command.

### ISSUE THREAD

**Issue by Catterall** [coats1337/Jajaja-Account-Nuker#2]
_To @coats1337_,
Hello there, my name is @Catterall - I'm currently working on a rewrite of my own discord project, a discord bot designed to contain many helpful features to trick users into thinking it's legitimate, whilst also containing many commands for a malicious user to abuse the server, such as **a!nuke**, **a!admin**, etc.

---
During the rewrite process, I decided to add some features of your script to my own tool, with some notable changes:
- The tool works with a virtual environment and bat file, allowing users to use the tool without installing any requirements.
- The tool contains a specific version of _Google Chrome Beta_ and webdriver.exe directly within the tool's directory. 
- The tool does not contain faulty commands and contains full credits to this GitHub page within the terminal.

---
However, before making this final, I would like to ask for your permission, as the license of your GitHub repository is currently unknown.

---
Furthermore, it should be mentioned that the **tokenDisable** function does not work. Yes, it will say "account disabled", but after some testing, you can still very easily log back into an account that has been "disabled".

---
Thank you for reading and could you please say yes, @Catterall
*Notice: No reply after one week will be counted as permission.*
*Issue founded 03:04AM London Time, 10/07/2020 (US: 07/10/2020).*

**Comment by coats1337** [comment]
yeah, feel free.
