### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Neoniktk** [coats1337/Jajaja-Account-Nuker#3]
![image](https://user-images.githubusercontent.com/67610464/87239396-3ea97f00-c3d4-11ea-96b5-cf33d652f0e0.png)
I have used
```
py -m pip install colorama
py -m pip install discord.py
py -m pip install requests
py -m pip install selenium
```

**Comment by coats1337** [comment]
linux user?

**Comment by Neoniktk** [comment]
No Windows 10

**Comment by coats1337** [comment]
mind running it in normal command prompt rather than git one?

**Comment by Neoniktk** [comment]
fixed
